version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    restart: always

  python-service:
    build:
      context: .
      dockerfile: Dockerfile.python
    working_dir: /app
    volumes:
      - ./model_training:/app
    restart: unless-stopped
