version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
